### PR TITLE
Feature/19 navigation

### PR DESCRIPTION
**Pull request by steevevadakkumchery**

### CODE REVIEW

**Comment by yoavaviram** [comment]
Thanks @steevevadakkumchery, looks good to me. A few comments:

- Can you take a look at why some tests are flailing? May be the same issue @limptwiglet just fixed on feature/ccpa-gdpr.
- @limptwiglet are you Ok with the use of Prettier?
- @roughprada maybe the menu should be sticky?

Anyway, well done!

**Comment by roughprada** [comment]
Interesting, the menu looks sticky to me? What browser are you using? We
have now mob nav!!

**Comment by gerrardmark** [comment]
> Thanks @steevevadakkumchery, looks good to me. A few comments:
> 
> * Can you take a look at why some tests are flailing? May be the same issue @limptwiglet just fixed on feature/ccpa-gdpr.
> * @limptwiglet are you Ok with the use of Prettier?
> * @roughprada maybe the menu should be sticky?
> 
> Anyway, well done!

The tests are failing for the same reason as my branch.
I don't mind using Prettier, it would be good to make sure we split our formatting changes from our code changes so its easier to review.

**Comment by limptwiglet** [comment]
> Thanks @steevevadakkumchery, looks good to me. A few comments:
> 
> * Can you take a look at why some tests are flailing? May be the same issue @limptwiglet just fixed on feature/ccpa-gdpr.
> * @limptwiglet are you Ok with the use of Prettier?
> * @roughprada maybe the menu should be sticky?
> 
> Anyway, well done!

The tests are failing for the same reason as my branch.
I don't mind using Prettier, it would be good to make sure we split our formatting changes from our code changes so its easier to review.

**Comment by yoavaviram** [comment]
@limptwiglet what was the fix for the failing tests?
@steevevadakkumchery can you move the Prettier changes to a separate PR? Also, can you add tests for the new code?

**Comment by yoavaviram** [comment]
Hi @steevegv, let me know when this PR is ready to be merged.

**Comment by yoavaviram** [comment]
I've deployed this [here](https://opt-out-eu-eezruxqbsh.now.sh/).

My comments:

1. Not sure why but this branch does not have the CCPA copy. @steevegv please merge master into it.
2. Change text for "Search Company" button to "Search Organizations"
3. When the home page first loads, clicking the search button is un-intuitive since the search bar is already in focus and it seems like nothing happens. Is there some sort of visual feedback we can give the user so that they understand that the focus is on the search bar?
4. On mobile nav the order of menu items is different, is this intentional @roughprada ?
5. On mobile nav the Search button looks strange, see attached image. 
6. On mobile nav there are additional items, is this intentional @roughprada ? 
7. On mobile nav there's an item titled contact us which takes you to the extension section. I suggest that we remove it.

Please give me your thoughts on these and we can then asses what is critical and what can wait. 

Screenshot 2019-11-21 at 10 05 22

**Comment by yoavaviram** [comment]
@roughprada wrote (on slack):

1. @steevegv  can you add the latest master into it with the CCPA copy?
2. ok
3. This is absolutellly right. @steevegv  can we show on-focus state into the box? similar to the links or content when we navigate with keyboard?
4. Yes, thisis to accomodate also the items that appear in the footer for ease.
5. @steevegv  can we make it wide enough so the text in the button doesn’t go into 2 lines?
6. same as 4
7. @steevegv This one should be a mailto to info@opt-out.com

**Pull request merged**
