### PR TITLE
90-extension-helper-homepage

### PR DESCRIPTION
**Pull request by steevevadakkumchery**

### CODE REVIEW

**Comment by yoavaviram** [comment]
Hello...
Anything I can help with?

**Comment by steevevadakkumchery** [comment]
Hi Yoav! 

Nice to meet you! I just spoke with Rafa today about some tickets in detail, I’ve had a look at the code today and I’ll probably write some code tomorrow.

Btw, I’ve been meaning to ask you. Have you used styled-components before? I’ve been using it quite a bit at work and I’ve seen it on a lot of React courses and the boot camp that I went to. If you have, do you reckon it will be something that we could start using on this project?

If we decide to do so, it shouldn’t effect any of the current code or styling, it will only effect new components.

I’m looking forward to your verdict. I don’t want to step on any toes since I’ve just joined the team! And I’m not too stubborn about it either, if we use it, it just means I can start working with my current skills.

Also! It’ll be good to speak to in person sometime. Maybe we can set up a call with Rafa sometime when he’s back.

Regards,
Steeve

**Comment by yoavaviram** [comment]
Hi Steeve,

Nice to meet you as well, thanks for helping!

I'm not familiar with styled-comonents. To be honest, my coding days are long gone, I'm doing what I can on this project but it's not much. My thoughts are that on the one hand it's awesome if there's a skill you can learn while working on Opt Out, but on the other hand I'd rather keep the code base consistent so that new contributors only need to learn one set of technologies / coding styles. I'm concerned that over time the code will accumulate more and more styles every time some new tech is trending (and there's no lack of that on the fronend). What do you think?

Happy to chat whenever convinient.

Thanks again, 

Yoav

**Comment by steevevadakkumchery** [comment]
Hi Yoav, that's a fair point! From what I've seen on the tickets, I should be fine using the current technologies anyways, I was just curious what you thought. But I think you're right, it might make it more difficult for future developers as they would have to learn something new.

**Comment by yoavaviram** [comment]
Let me knwo when this pull request is ready.

How about a phone call on Tomorrow or Tuesday?

**Comment by steevevadakkumchery** [comment]
This PR is sort of ready, all the styling is done to what I think looks consistent. I feel like the text on the whole page is different from the Zeplin file, might be easier/quicker to do the text manually and make components for header, paragraphs etc . . . For now I've tried to use the Typography component in most places. Also the logos on Zeplin changed as I was working on it, and now it's not letting me download the assets for some reason. I also don't have the links for the extensions, so I haven't added a link to any of the buttons. I have also not added the github icon as I couldn't download that either. So as soon as some of these are clarified and the assets become downloadable, I can edit the PR to a state that is able to go to Master.

**Comment by roughprada** [comment]
Hey Steeve, thanks for the update!

I don't have access to a computer untill the 25th, and I cannot check the
stylings, but I can give you few answers

Text:
We are using material for react and the typography can be found here:
https://material-ui.com/customization/typography/

We know is not alifn with the zeplin files, please follow consistency with
the other life ve components, zeplin is a guide.

I last checked it on saturday, and the buttons didn't look consistent with
the rest of the site. I looked into the material guide and found this:
https://material-ui.com/components/buttons/

Based on that, I changed the icons using font awesome:
Chrome https://fontawesome.com/icons/chrome?style=brands
Ff https://fontawesome.com/icons/firefox?style=brands

Links to the extensions:
Chrome
https://chrome.google.com/webstore/detail/opt-out-one-click-gdpr-er/dedldhojjkgbejnmmfpmbnbihmmpfbpd
FF https://addons.mozilla.org/en-GB/android/addon/opt-out/

I've also noticed that there are 2 sizes of components, and this particular
one will benefit from being a bit wider. Can we compare and align with the
"how it works" one?

And lastly, please make sure that this component is separated from the old
social one, as that one is shared accross few places and it will be best if
this is a variant of it.



Kind regards,
Rafa Prada





This email and any attachments may contain information that is confidential
and privileged. It is intended to be received only by persons entitled to
receive the information. If you are not the intended recipient, please
delete it from your system and notify the sender. You should not copy it or
use it for any purpose nor disclose or distribute its contents to any other
person.

**Comment by yoavaviram** [comment]
@roughprada when you're back, can you update the zeplin files to make them consistent with the website in terms of design decisions we've made (github) and copy?

**Comment by yoavaviram** [comment]
@steevevadakkumchery can you take a look at the tests? One is failing at the moment.

**Comment by roughprada** [comment]
@yoavaviram I am happy with the designs, please let me know if you'd like to revisit the copy, otherwise, I am happy to release.

**Comment by yoavaviram** [comment]
Nice work @steevevadakkumchery ! I've got three comments:

- Please make the order of the social icons the same as in the live site
- Change copy to: "Do you want better control over who has access to your personal data? Our browser extension allows you to opt out of the websites you visit with a click of a button."
- Please add analytics tracking when clicking the extension buttons (see how it's done on the social icons)
- Can we add a nav link for to navigate to the extension section? (@roughprada does this make sense?) 

Other then these it is ready to be merged.

**Comment by roughprada** [comment]
Yes, all good. My only concern is that the nav is crap on mobile and it
wouldn't accomodate any more content.

Saying that I guess the best strategy is to add it now, and look at it on
#19 more in depth.

Steeve, can you add a link to "Extensions"?

After a light research, extensions are not wide spread, but for now, is the
most accurate.

>

**Comment by roughprada** [comment]
@steevevadakkumchery @yoavaviram I just made the changes that Yoav requested, all ready to merge

**Pull request merged**
